### ISSUE TITLE
EMS/FD Job Issues

### ISSUE THREAD

**Issue by Hio102** [rgalusha/TheBigEasy-Issue-Tracker#15]
Got a couple here (F-21 writing this)
No extras menu for vehicles
No access to /bill command
No Job Hire/Fire menu (intended?)
No Vehicle Spawner
Need locks on more hospital doors - the room where we get radios/bandages is unlocked (no lock on the door). The staff areas should be locked too, as well as the other hospital wings/offices

**Comment by rgalusha** [comment]
Resolved
