### ISSUE TITLE
Evidence Lockers

### ISSUE THREAD

**Issue by Friskky3** [rgalusha/TheBigEasy-Issue-Tracker#4]
Suggestion Title: Evidence Lockers

Suggestion Summary: Evidence lockers should be added at Paleto bay, Sandy and Los Santos Police Station. So then when we arrest criminals we have a spot to put there "belongings" so we don't keep it on us or throw it away

Explain Expected Benefit to Community: Pretty self explanatory on why we need it.

**Comment by rgalusha** [comment]
Thank you for the suggestion. They are implemented within the Sheriff station and MRPD but are still to be added to other stations.

**Comment by Friskky3** [comment]
> Thank you for the suggestion. They are implemented within the Sheriff station and MRPD but are still to be added to other stations.

where is it located in MRPD?

**Comment by rgalusha** [comment]
Resolved
