### ISSUE TITLE
clothing icon in MRPD not working for me

### ISSUE THREAD

**Issue by cryptic-militia** [rgalusha/TheBigEasy-Issue-Tracker#9]
Not sure if this is just a me issue, however i relogged a few times. I cannot change clothes at MRPD
![image](https://user-images.githubusercontent.com/82733745/115129029-d2cdf580-9fa7-11eb-98e4-e8f689650bb5.png)

**Comment by rgalusha** [comment]
Could you try to see if its not working again? I think it should be fixed now.

**Comment by cryptic-militia** [comment]
hey was busy with work. couldnt get in today. i believe server is offline

**Comment by rgalusha** [comment]
Resolved
